-- 1. 전체 학생 목록 조회
SELECT * FROM STUDENT;

-- 2. 2학년 이상 학생 조회
SELECT STUDENT_ID, NAME, GRADE
FROM STUDENT
WHERE GRADE >= 2;

-- 3. 컴퓨터소프트웨어과 학생만 조회
SELECT STUDENT_ID, NAME, DEPT
FROM STUDENT
WHERE DEPT = '컴퓨터소프트웨어과';

-- 4. 교수 목록 조회
SELECT * FROM PROFESSOR;

-- 5. 김진숙 교수가 담당하는 강의 목록
SELECT C.COURSE_ID, C.TITLE, C.CREDIT
FROM COURSE C
JOIN PROFESSOR P ON C.PROFESSOR_ID = P.PROFESSOR_ID
WHERE P.NAME = '김진숙';

-- 6. 각 강의별 수강 인원 수
SELECT C.TITLE, COUNT(E.ENROLL_ID) AS ENROLL_CNT
FROM COURSE C
LEFT JOIN ENROLL E ON C.COURSE_ID = E.COURSE_ID
GROUP BY C.TITLE
ORDER BY ENROLL_CNT DESC;

-- 7. 각 학생이 수강 중인 과목 목록
SELECT S.NAME AS STUDENT_NAME, C.TITLE AS COURSE_TITLE
FROM ENROLL E
JOIN STUDENT S ON E.STUDENT_ID = S.STUDENT_ID
JOIN COURSE  C ON E.COURSE_ID = C.COURSE_ID
ORDER BY S.NAME;

-- 8. 특정 학생(김철수)의 출결 내역
SELECT S.NAME, C.TITLE, A.ATTEND_DATE, A.STATUS
FROM ATTENDANCE A
JOIN ENROLL E ON A.ENROLL_ID = E.ENROLL_ID
JOIN STUDENT S ON E.STUDENT_ID = S.STUDENT_ID
JOIN COURSE C  ON E.COURSE_ID = C.COURSE_ID
WHERE S.NAME = '김철수'
ORDER BY A.ATTEND_DATE;

-- 9. 특정 강의(데이터베이스)의 전체 출결 내역
SELECT C.TITLE, S.NAME, A.ATTEND_DATE, A.STATUS
FROM ATTENDANCE A
JOIN ENROLL E ON A.ENROLL_ID = E.ENROLL_ID
JOIN STUDENT S ON E.STUDENT_ID = S.STUDENT_ID
JOIN COURSE C  ON E.COURSE_ID = C.COURSE_ID
WHERE C.TITLE = '데이터베이스'
ORDER BY A.ATTEND_DATE, S.NAME;

-- 10. 학생별 출석(O) 횟수
SELECT S.NAME,
       SUM(CASE WHEN A.STATUS = 'O' THEN 1 ELSE 0 END) AS ATTEND_CNT
FROM STUDENT S
JOIN ENROLL E ON S.STUDENT_ID = E.STUDENT_ID
JOIN ATTENDANCE A ON E.ENROLL_ID = A.ENROLL_ID
GROUP BY S.NAME
ORDER BY ATTEND_CNT DESC;

-- 11. 학생별 총 수업 수 및 출석률
SELECT S.NAME,
       COUNT(*) AS TOTAL_CLASS,
       SUM(CASE WHEN A.STATUS='O' THEN 1 ELSE 0 END) AS ATTEND_CNT,
       ROUND(SUM(CASE WHEN A.STATUS='O' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS ATTEND_RATE
FROM STUDENT S
JOIN ENROLL E ON S.STUDENT_ID = E.STUDENT_ID
JOIN ATTENDANCE A ON E.ENROLL_ID = A.ENROLL_ID
GROUP BY S.NAME
ORDER BY ATTEND_RATE DESC;

-- 12. 결석(A) 횟수가 1회 이상인 학생 목록
SELECT DISTINCT S.NAME
FROM STUDENT S
JOIN ENROLL E ON S.STUDENT_ID = E.STUDENT_ID
JOIN ATTENDANCE A ON E.ENROLL_ID = A.ENROLL_ID
WHERE A.STATUS = 'A';

-- 13. 각 강의별 결석(A) 비율
SELECT C.TITLE,
       COUNT(*) AS TOTAL,
       SUM(CASE WHEN A.STATUS='A' THEN 1 ELSE 0 END) AS ABSENT_CNT,
       ROUND(SUM(CASE WHEN A.STATUS='A' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS ABSENT_RATE
FROM COURSE C
JOIN ENROLL E ON C.COURSE_ID = E.COURSE_ID
JOIN ATTENDANCE A ON E.ENROLL_ID = A.ENROLL_ID
GROUP BY C.TITLE
ORDER BY ABSENT_RATE DESC;

-- 14. 특정 기간(최근 3일) 출결 내역
SELECT S.NAME, C.TITLE, A.ATTEND_DATE, A.STATUS
FROM ATTENDANCE A
JOIN ENROLL E ON A.ENROLL_ID = E.ENROLL_ID
JOIN STUDENT S ON E.STUDENT_ID = S.STUDENT_ID
JOIN COURSE C  ON E.COURSE_ID = C.COURSE_ID
WHERE A.ATTEND_DATE >= TRUNC(SYSDATE) - 3
ORDER BY A.ATTEND_DATE DESC;

-- 15. 1001번 학생이 수강하는 과목명과 담당 교수명
SELECT S.STUDENT_ID, S.NAME, C.TITLE, P.NAME AS PROF_NAME
FROM STUDENT S
JOIN ENROLL E ON S.STUDENT_ID = E.STUDENT_ID
JOIN COURSE C ON E.COURSE_ID = C.COURSE_ID
JOIN PROFESSOR P ON C.PROFESSOR_ID = P.PROFESSOR_ID
WHERE S.STUDENT_ID = 1001;

-- 16. 교수별 평균 출석률
SELECT P.NAME AS PROF_NAME,
       ROUND(
         AVG(
           CASE WHEN A.STATUS='O' THEN 1 ELSE 0 END
         ) * 100, 2
       ) AS AVG_ATTEND_RATE
FROM PROFESSOR P
JOIN COURSE C ON P.PROFESSOR_ID = C.PROFESSOR_ID
JOIN ENROLL E ON C.COURSE_ID = E.COURSE_ID
JOIN ATTENDANCE A ON E.ENROLL_ID = A.ENROLL_ID
GROUP BY P.NAME
ORDER BY AVG_ATTEND_RATE DESC;

-- 17. 수강신청이 하나도 없는 강의 찾기
SELECT C.COURSE_ID, C.TITLE
FROM COURSE C
LEFT JOIN ENROLL E ON C.COURSE_ID = E.COURSE_ID
WHERE E.ENROLL_ID IS NULL;

-- 18. 출결 기록이 전혀 없는 수강(ENROLL) 찾기
SELECT E.ENROLL_ID, S.NAME, C.TITLE
FROM ENROLL E
JOIN STUDENT S ON E.STUDENT_ID = S.STUDENT_ID
JOIN COURSE C  ON E.COURSE_ID = C.COURSE_ID
LEFT JOIN ATTENDANCE A ON E.ENROLL_ID = A.ENROLL_ID
WHERE A.ATTENDANCE_ID IS NULL;

-- 19. 과목별로 수강 중인 학년(grade)의 분포
SELECT C.TITLE, ST.GRADE, COUNT(*) CNT
FROM COURSE C
JOIN ENROLL E ON C.COURSE_ID = E.COURSE_ID
JOIN STUDENT ST ON E.STUDENT_ID = ST.STUDENT_ID
GROUP BY C.TITLE, ST.GRADE
ORDER BY C.TITLE, ST.GRADE;

-- 20. 지각(T)이 1회 이상 있는 학생 목록
SELECT DISTINCT S.NAME
FROM STUDENT S
JOIN ENROLL E ON S.STUDENT_ID = E.STUDENT_ID
JOIN ATTENDANCE A ON E.ENROLL_ID = A.ENROLL_ID
WHERE A.STATUS = 'T';

-- 21. 특정 강의(자바프로그래밍)의 학생별 출석률
SELECT S.NAME,
       COUNT(*) AS TOTAL,
       SUM(CASE WHEN A.STATUS='O' THEN 1 ELSE 0 END) AS ATTEND_CNT,
       ROUND(SUM(CASE WHEN A.STATUS='O' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS RATE
FROM STUDENT S
JOIN ENROLL E ON S.STUDENT_ID = E.STUDENT_ID
JOIN COURSE C ON E.COURSE_ID = C.COURSE_ID
JOIN ATTENDANCE A ON E.ENROLL_ID = A.ENROLL_ID
WHERE C.TITLE = '자바프로그래밍'
GROUP BY S.NAME
ORDER BY RATE DESC;

-- 22. 오늘 날짜 기준으로 아직 수업이 없는 강좌(출결 데이터 없음)
SELECT C.COURSE_ID, C.TITLE
FROM COURSE C
LEFT JOIN ENROLL E ON C.COURSE_ID = E.COURSE_ID
LEFT JOIN ATTENDANCE A ON E.ENROLL_ID = A.ENROLL_ID
    AND A.ATTEND_DATE = TRUNC(SYSDATE)
WHERE A.ATTENDANCE_ID IS NULL;
