-------------------------------------------------
-- STUDENT
-------------------------------------------------
INSERT INTO STUDENT VALUES (SEQ_STUDENT.NEXTVAL, '김철수', '컴퓨터소프트웨어과', 2, '010-1111-1111');
INSERT INTO STUDENT VALUES (SEQ_STUDENT.NEXTVAL, '이영희', '컴퓨터소프트웨어과', 1, '010-2222-2222');
INSERT INTO STUDENT VALUES (SEQ_STUDENT.NEXTVAL, '박민수', '컴퓨터소프트웨어과', 3, '010-3333-3333');

-------------------------------------------------
-- PROFESSOR
-------------------------------------------------
INSERT INTO PROFESSOR VALUES (SEQ_PROFESSOR.NEXTVAL, '김진숙', '컴퓨터소프트웨어과');
INSERT INTO PROFESSOR VALUES (SEQ_PROFESSOR.NEXTVAL, '이상훈', '컴퓨터공학과');

-------------------------------------------------
-- COURSE
-------------------------------------------------
INSERT INTO COURSE VALUES (SEQ_COURSE.NEXTVAL, '데이터베이스', 3, 2001);
INSERT INTO COURSE VALUES (SEQ_COURSE.NEXTVAL, '자바프로그래밍', 3, 2001);
INSERT INTO COURSE VALUES (SEQ_COURSE.NEXTVAL, '운영체제', 3, 2002);

-------------------------------------------------
-- ENROLL (수강신청)
-------------------------------------------------
-- 김철수(1001) : 데이터베이스(3001), 자바(3002)
INSERT INTO ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 1001, 3001);
INSERT INTO ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 1001, 3002);

-- 이영희(1002) : 데이터베이스(3001)
INSERT INTO ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 1002, 3001);

-- 박민수(1003) : 자바(3002), 운영체제(3003)
INSERT INTO ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 1003, 3002);
INSERT INTO ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 1003, 3003);

-------------------------------------------------
-- ATTENDANCE (출결정보)
-- ENROLL_ID는 실제 생성된 값 확인 후 수정할 수 있음 (여기선 4001부터 순차라고 가정)
-------------------------------------------------
-- 김철수 - 데이터베이스
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4001, TRUNC(SYSDATE)-3, 'O');
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4001, TRUNC(SYSDATE)-2, 'T');
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4001, TRUNC(SYSDATE)-1, 'O');

-- 김철수 - 자바
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4002, TRUNC(SYSDATE)-2, 'A');
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4002, TRUNC(SYSDATE)-1, 'O');

-- 이영희 - 데이터베이스
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4003, TRUNC(SYSDATE)-3, 'O');
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4003, TRUNC(SYSDATE)-2, 'O');
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4003, TRUNC(SYSDATE)-1, 'O');

-- 박민수 - 자바, 운영체제
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4004, TRUNC(SYSDATE)-2, 'O');
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4004, TRUNC(SYSDATE)-1, 'A');

INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4005, TRUNC(SYSDATE)-2, 'T');
INSERT INTO ATTENDANCE VALUES (SEQ_ATTENDANCE.NEXTVAL, 4005, TRUNC(SYSDATE)-1, 'O');

COMMIT;
